New Command to setup developement environnement from dev branch
friends-of-presta/fop_console pull request #108
Opened 2021-03-23 09:25 UTC by Mch0

Questions | Answers
-- | --
Command name? | the command name "fop:install-env-for-dev"
Command description? | Setup your local environnement for dev
Command domain? | dev
Command parameters? | url = url to set for your env, ssl = want you active ssl, modifyemployeepwd = change all employee password, modifycustomerpwd = change all customers password

Here details of Command :

- Update your developement url into configuration table and shop_url table 
- Update ssl mode into configuration table
- Regenerate htaccess
- If set in option => you can change all employees BO password
- If set in option => you can change all customers password
- Enable debug mode
- Set smart cache (css and js) to false
- Set global cache to false
- Disable smarty cache, force template recompilation, use cache file system
- Disable maintenance mode
- Clear all cache

2021-03-29 15:19 UTC, jf-viguier commented
@Mch0 Pourquoi changer les passwords client et employés ?

2021-03-29 15:22 UTC, Mch0 commented
@jf-viguier, pcq pour faire des tests sur des comptes client ou autres, c'est pratique, si tu as besoin de faire un test sur un client qui a un groupe tarrifaire particulier ou groupe client particulier ou les deux. Ou encore tester un client d'un autre pays etc. Pour les comptes BO c'est juste histoire d'avoir toujours le meme mot de passe pour le compte BO que jj'utilise sur mon local

2021-04-05 16:40 UTC, SebSept commented
Dans mes petits scripts maison, je fais presque la même chose. Je créé un nouvel admin et un nouveau client.
L'inconvénient de faire comme tu fais, c'est que tu ne peux pas ensuite remetre la base en prod.
Vu que c'est une option et que ça à du sens pour toi, c'est ok pour moi sur ce point.

2021-04-05 16:44 UTC, SebSept commented
J'ai lancé l'aide avant de me lancer dans la lecture du code, comme le feront les utisateurs.

- [ ] Dans l'aide, tu peux expliquer comment fonctionne le changement de mots de passe ?
- [ ] Il manque pas un verbe dans `This command database configuration with dev parameters (url,ssl)` ?
- [ ] l'option shop_id, c'est pour quoi (je bosse jamais sur du multiboutique) ?

2021-04-05 17:18 UTC, SebSept commented
Merci pour cette contribution :)
C'est une commande qui me manque beaucoup en 1.7 ! (j'avais mon petit truc en 1.6).
ça va être bien pratique 👍🏼

Mes premières remarques :

-  Il faudrait que la commande puisse être utilisée dans des scripts, sinon elle perd beaucoup de valeur pour moi. Autrement dit, il faut qu'elle se comporte correctement si on ajoute l'option --no-interaction (dans un script, on est dans ce mode).
- le changement d'url ne devrait pas se faire si on spécifie pas une (c'est lié au premier point).
- on ne peut pas spécifier le mot de passe en argument (-> commande pas utilsable en script non interactif, moins d'interaction = moins de risque d'erreur, moins de temps passé)
- il (me) manque la possibilité de spécifier le dossier de la boutique (physical_uri). Pour moi, c'est obligatoire, je fais pas des vhosts et j'ai mes sites prestashop dans des sous-dossiers (/pro/clientmachin , /pro/clientbidule/ , ...)
- c'est moins important mais la fonction principale est peu longue, tu as mis des commentaires pour délimiter les parties, c'est bien lisible mais avec des petites fonctions (une pour le cache smary, etc, on pourrait peut-être avec l'ensemble du code de execute() sur une page écran, ça serait top.

Finalement, c'est surtout une question de gestion des options et interactions, le code en lui même me semble très bien 👍🏼

2021-04-05 17:29 UTC, SebSept commented
Et ça fonctionne bien les transactions, tu as testé avec une partie qui échoue ?
Pas besoin de capturer les exceptions ça ?

2021-04-06 16:52 UTC, Mch0 commented
Oula bcp de réponse à faire :)

> Dans mes petits scripts maison, je fais presque la même chose. Je créé un nouvel admin et un nouveau client.
> L'inconvénient de faire comme tu fais, c'est que tu ne peux pas ensuite remetre la base en prod.
> Vu que c'est une option et que ça à du sens pour toi, c'est ok pour moi sur ce point.

Concernant le fait de remettre une base de dev en Prod, ça me choque, c'est une chose que je ne ferais jamais et que je n'ai jamais fait hormis les nouveaux sites ou la preprod devient la prod, mais dans ce cas là il n'y pas de client encore inscrit sur le site etc

2021-04-06 16:54 UTC, Mch0 commented
> J'ai lancé l'aide avant de me lancer dans la lecture du code, comme le feront les utisateurs.
> 
> * [ ]  Dans l'aide, tu peux expliquer comment fonctionne le changement de mots de passe ?
Je peux expliquer plus en détail
> * [ ]  Il manque pas un verbe dans `This command database configuration with dev parameters (url,ssl)` ?
Si je vais revoir la phrase
> * [ ]  l'option shop_id, c'est pour quoi (je bosse jamais sur du multiboutique) ?
C'est pour le multiboutique notament pour affecter l'url à une boutique en particulier, c'est pour ça que changer le mdp des clients et comptes BO est optionnel.

2021-04-06 16:57 UTC, Mch0 commented
> Merci pour cette contribution :)
> C'est une commande qui me manque beaucoup en 1.7 ! (j'avais mon petit truc en 1.6).
> ça va être bien pratique 👍🏼
> 
> Mes premières remarques :
> 
> * Il faudrait que la commande puisse être utilisée dans des scripts, sinon elle perd beaucoup de valeur pour moi. Autrement dit, il faut qu'elle se comporte correctement si on ajoute l'option --no-interaction (dans un script, on est dans ce mode).

Dans quel cas d'usage tu voudrais l'utiliser, as-tu un exemple plus précis ?

> * le changement d'url ne devrait pas se faire si on spécifie pas une (c'est lié au premier point).
Point à corriger

> * on ne peut pas spécifier le mot de passe en argument (-> commande pas utilsable en script non interactif, moins d'interaction = moins de risque d'erreur, moins de temps passé)
> * il (me) manque la possibilité de spécifier le dossier de la boutique (physical_uri). Pour moi, c'est obligatoire, je fais pas des vhosts et j'ai mes sites prestashop dans des sous-dossiers (/pro/clientmachin , /pro/clientbidule/ , ...)

Pas de connaissance de cela, il y a une doc là dessus? Pas sûr de comprendre

> * c'est moins important mais la fonction principale est peu longue, tu as mis des commentaires pour délimiter les parties, c'est bien lisible mais avec des petites fonctions (une pour le cache smary, etc, on pourrait peut-être avec l'ensemble du code de execute() sur une page écran, ça serait top.

On peu découper le code oui
 
> Finalement, c'est surtout une question de gestion des options et interactions, le code en lui même me semble très bien 👍🏼
> (Il est possible de garder le coté interactif et de gerer le coté fonctionnement sans interaction, c'est pas forcément contraditoire)

On peu faire en sorte de traiter l'option --no-interaction et du coup pas de question etc lors du lancement de la commande

2021-04-07 08:33 UTC, SebSept commented
> Dans quel cas d'usage tu voudrais l'utiliser, as-tu un exemple plus précis ?
je m'en sert pour copier la base de production sur ma machine pour deboger
```
ssh dist "mysqldum ..." # dump de la base de prod
rsync dist:/tmp/base.sql.gz ./.... # copie de la base sur ma machine
./bin/console fop:dev:setup-env # adaptation de la base à l'env de ma machine
```

2021-04-07 08:35 UTC, SebSept commented
> On peu faire en sorte de traiter l'option --no-interaction et du coup pas de question etc lors du lancement de la commande
Si justement, on peut garder la possibilité de poser des questions, mais uniquement en mode interactif.
Je l'ai déjà fait ... (dans la commande override ou d'export des config peut-être)

2021-04-07 08:39 UTC, SebSept commented
le physical_uri, c'est un champ de la table ps_shop_url pour indiquer si le site ne se trouve pas à la racine web.

2021-04-07 16:52 UTC, SebSept commented
> Concernant le fait de remettre une base de dev en Prod, ça me choque

C'est l'inverse en fait prod -> dev

2021-04-07 17:02 UTC, SebSept commented
Au passage, tu pourrai aussi virer les doc bloc et typer les arguments et les retours de fonctions.
Bye bye php 5!
```php
protected function updateUrlConfiguration(int $idShop, string $url): bool
```
tu me dis, si j'en demande trop !

2021-04-07 17:14 UTC, Mch0 commented
J'ai rajouté les types de retour, par contre je laisse des blocs de doc, j'ai aussi rajouté les types pour les paramètres des méthodes

2021-04-07 17:23 UTC, SebSept commented
Quelle est l'utilité de garder les docbloc ? pour vscode ?

2021-05-31 14:59 UTC, Mch0 commented
@SebSept j'ai ajouté les options pour mettre la physical et/ou la virtual uri.
Pour le reste j'appel à mes collègues pour review la command :)

2021-06-02 08:06 UTC, Mch0 commented
@okom3pom ,

Si tu veux tu peux ajouter ton code et faire des modifs sur la commande :) et pousser les modifs/correctifs, pas de soucis pour moi, puis je refuse pas un peu d'aide :)

2021-06-02 13:00 UTC, SebSept commented
Je vais regarder ça dans les jours qui viennent..

2021-06-07 14:25 UTC, SebSept commented
bon, pas eu le temps de regarder ce weekend (trop de soleil et d'apéro :D ) 
En plus, pour pas mélanger tout, j'attend déjà que mon PR soit mergé.

2021-06-11 10:13 UTC, SebSept commented
je vois que les options sont au format 'modifyemployeepwd' , c'est pas hyper lisible.
`modify-employee-pwd` ou `modify_employee_pwd` serait pas mieux ?
Git utilise le tiret, symfony aussi.
ça serait surement mieux comme ça `modify-employee-pwd`

2021-06-11 10:15 UTC, SebSept commented
il y a besoin 2 options pour modifier les mots de passe `--modifyemployeepwd 1` + `--employeepwd=EMPLOYEEPWD`.
C'est utile d'avoir les 2 ? On peut pas juste avoir `--employeepwd <new_password>` ?

2021-06-11 10:23 UTC, SebSept commented
ok, je comprend, tu peux spécifier l'option `--modifyemployeepwd` sans `--employeepwd` pour avoir la demande interactive et juste `--employeepwd`  pour le définir sans passer par l'interaction.

2021-06-11 10:27 UTC, SebSept commented
du coup, il y a pas d'utilité a avoir une valeur sur l'option modifyemployeepwd (et modifycustomerpwd).

2021-06-11 10:46 UTC, SebSept commented
l'option  --employeepwd ne fonctionne que si on met aussi l'option  -modifyemployeepwd 
il faudrait qu'on puisse utiliser simplement --employeepwd sans --modifyemployeepwd

2021-06-11 12:08 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +     * @param $idShop
```
@param int $idShop
@param string $url
```
manque les types.

2021-06-11 12:08 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +     * @param $idShop
```
     * @param int $idShop
     * @param bool $ssl
     ```

2021-07-23 14:26 UTC, Mch0 commented
Pour moi on est pas mal pour une première bonne version je pense. Il manque juste une review pour qu'on soit ok

2021-09-30 19:45 UTC, SebSept requested changes
yeah, that's really better like that :) 👍🏼 
I've proposed some light changes. `Host` is more clear than `url` to me.

Additional advice : stop using the return values of the methods.
At the end, if there is an error, we are warned but we don't know the error.
You'd better use Exceptions, that really simpler and give explicit errors.

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +    protected function enableDecbugMode(): int
```suggestion
    protected function enableDebugMode(): int
```
just a typo.

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +        $this->enableDecbugMode();
```suggestion
        $this->enableDebugMode();
```
just a typo.

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +                        '<info>php bin/console fop:dev:setup-env --url=url.local --modify-employee-pwd=1 --modify-customer-pwd=1 --employee-pwd=fopisnice --customer-pwd=fopisnice --ssl=0</info>'
```suggestion
                        '<info>php bin/console fop:dev:setup-env --host=localhost --purl="/pro/clients/jojo/"  --modify-employee-pwd=1 --modify-customer-pwd=1 --employee-pwd=fopisnice --customer-pwd=fopisnice --ssl=0</info>'
```
2 changes here : 
- `url` param is renamed `host` (must be check on other places)
- `purl` param is added

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +        $this->addUsage('--url=[url]');
```suggestion
        $this->addUsage('--host=[localhost]');
```

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +        $this->addOption('url', 'u', InputOption::VALUE_REQUIRED, 'url to set');
```suggestion
        $this->addOption('host', 'u', InputOption::VALUE_REQUIRED, 'host to set');
```

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +        $url = $input->getOption('url') ?? $this->helper->ask($input, $output, new Question('<question>Please, specify the url you want for your env actualy  : ' . $shop->domain . ' Press enter for t
```suggestion
        $host = $input->getOption('host') ?? $this->helper->ask($input, $output, new Question('<question>Please, specify the host you want for your env, currently  : ' . $shop->domain . ' Press enter for the same</question>'));
```

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +        $puri = $input->getOption('purl') ?? $this->helper->ask($input, $output, new Question('<question>Please, specify the phisical url you want for your env actualy : ' . $shop->physical_uri . ' P
```suggestion
        $puri = $input->getOption('purl') ?? $this->helper->ask($input, $output, new Question('<question>Please, specify the physical url you want for your env, currently : ' . $shop->physical_uri . ' Press enter for the same</question>'));
```

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +        if (!$url) {
```suggestion
        if (!$host) {
```

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +            $url = $shop->domain;
```suggestion
            $host = $shop->domain;
```

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +        $res = $res && $this->updateUrlConfiguration($idShop, $url);
```suggestion
        $res = $res && $this->updateUrlConfiguration($idShop, $host);
```

2021-09-30 19:45 UTC, SebSept commented on src/Commands/DevSetupEnv.php
> +        $res = $res && $this->updateShopUrl($idShop, $url, $puri, $vuri);
```suggestion
        $res = $res && $this->updateShopUrl($idShop, $host, $puri, $vuri);
```

2021-10-01 07:41 UTC, okom3pom commented
Hello,

This PR need a rebase for conflict.

Nice job

2021-10-01 07:51 UTC, SebSept commented
it means [this](https://github.com/githubteacher/github-for-developers-sept-2015/issues/648#issuecomment-144488223)  @okom3pom , right ?

2021-10-01 08:01 UTC, okom3pom commented
I use this way for Prestashop https://github.com/okom3pom/useful/blob/main/rebase.md

2021-10-01 08:17 UTC, SebSept commented
Thanks. 
I have no idea of the recommended way (but not a huge fan of a `--force` on principle).

2021-10-01 08:23 UTC, okom3pom commented
En français du coup

C'est le tuto de @Progi1984, je l'utilise pour tous mes rebase sur PrestaShop ici @Mch0 peut utiliser l'éditeur de github c'est un petit conflit.

Voir image :

![Capture d’écran de 2021-10-01 10-21-36](https://user-images.githubusercontent.com/5064590/135588864-8aa47171-11ea-401e-881d-fb5880a59d56.png)

2021-10-01 08:44 UTC, SebSept approved these changes

2021-10-01 08:45 UTC, merged