Fix more typos
friends-of-presta/fop_console pull request #134
Opened 2021-06-22 23:13 UTC by mickaelandrieu

2021-06-23 05:50 UTC, okom3pom approved these changes

2021-06-23 15:41 UTC, jf-viguier commented
@mickaelandrieu pourquoi enlever la liste des commandes ?

2021-06-23 15:53 UTC, okom3pom commented
@jf-viguier elle est en double dans le readme :)

2021-06-24 19:04 UTC, nenes25 requested changes
Beware because the command fop:module:hooks is not present on the second list.

2021-07-01 19:55 UTC, SebSept commented
Fixed.
Thanks @mickaelandrieu .

2021-07-01 19:55 UTC, closed without merging

2021-07-01 19:56 UTC, SebSept reviewed
done. full list.