Add badges
friends-of-presta/fop_console pull request #157
Opened 2021-07-12 16:44 UTC by okom3pom

2021-07-12 16:54 UTC, jf-viguier approved these changes

2021-07-12 18:53 UTC, nenes25 requested changes
De mémoire on était parti sur la version 7.2 de php au minimum
![image](https://user-images.githubusercontent.com/7163132/125340909-50a95f00-e353-11eb-8a15-370d548fa3a8.png)

d'ou cette vérif => https://github.com/friends-of-presta/fop_console/blob/dev/fop_console.php#L41
( Il faudrait qu'on mettes à jour le fichier composer.json au passage, il me semblait que c'était figé aussi )

2021-07-12 19:45 UTC, SebSept commented
oui, c'est 7.2+

2021-07-13 04:35 UTC, okom3pom commented
Oups j'ai regardé la version qui correspondait à la 1.7.5

2021-07-13 12:49 UTC, nenes25 approved these changes

2021-08-09 11:53 UTC, merged