WIP : Add environment:getenv command
friends-of-presta/fop_console pull request #251
Opened 2022-05-09 16:46 UTC by MeKeyCool

I am currently working on environment variables for Prestashop and I need an easy command to make my development / tests easier.

This command is under work but I let it there to enjoy automatic tests and to receive comments or ideas for improvements ;)
If it is a problem, I can close it :)

2022-05-10 06:50 UTC, SebSept commented
Thanks for contribution 🎉 

Looks fine but : 
- The command name / service name / classname must be consistent ( https://github.com/friends-of-presta/fop_console/runs/6364780235?check_suite_focus=true) - Currently there no tool to help you naming it, you should look at the existing ones to get information (#212) - (This should also be written in our contributing file).
- just a question : how does it behave it an env value is not defined ?

2022-05-10 07:58 UTC, MeKeyCool commented
> Thanks for contribution tada
> 
> Looks fine but :
> 
>     * The command name / service name / classname must be consistent ( https://github.com/friends-of-presta/fop_console/runs/6364780235?check_suite_focus=true) - Currently there no tool to help you naming it, you should look at the existing ones to get information ([DevTool : command to generate Class name, service name from a command name. #212](https://github.com/friends-of-presta/fop_console/issues/212)) - (This should also be written in our contributing file).
> 
>     * just a question : how does it behave it an env value is not defined ?

Sorry it is still a draft but yes I will make it safier (testing if parameter exists before getting it)

Ok, I will add some comments/descriptions to the command ^^

For naming / standards, I'll try to understand and fix problem returned by CI ^^

2022-05-10 10:31 UTC, SebSept commented
@tom-combet do you have a minute for the service name ? 
It looks correct but failed ... (I'll check too, later).

2022-05-10 11:21 UTC, tom-combet commented
@SebSept It should be get_env instead of getenv.

2022-05-10 11:22 UTC, tom-combet commented
@MeKeyCool Thanks for contribution!
I'll review it next week, too busy right now sry...

2022-05-10 12:15 UTC, SebSept commented on src/Commands/Environment/EnvironmentGetEnv.php
> +            ->setAliases(['fop:environment:getenv'])
```suggestion
        $this->setName('fop:environment:get-env')
```
the alias is not needed. (it was for backward compat on other commands)

2022-05-10 12:15 UTC, SebSept commented on config/services.yml
> +  fop.console.environment.getenv.command:
```suggestion
  fop.console.environment.get_env.command:
```

2022-05-10 13:18 UTC, SebSept commented
service name must be `fop.console.environment.get_env.command` (you overwrote my commit 😭 😄 ).

2022-05-10 15:00 UTC, MeKeyCool commented on config/services.yml
> +  fop.console.environment.getenv.command:
Thx for help, I'll change this from my repos to avoid useless commits ;)

2022-05-13 20:17 UTC, SebSept requested changes
Thanks @MeKeyCool for you first contribution :) 
The command works fine and the parameters are in the help message, that's all good :) 

Undefined values are spotted with a red background, that good.
I suggest, you do the same for boolean values. 
Currently it's not possible to know if a configuration is `false` or an empty string, maybe you can render the boolean `true` and `false` with <note> or <comment> style.

The other point it that it's can be better to have a try/catch block to avoid unclear errors that may happen (but will probably never happen). (not mandatory, but better imo)

2022-05-16 08:22 UTC, MeKeyCool commented
> Thanks @MeKeyCool for you first contribution :) The command works fine and the parameters are in the help message, that's all good :)
> 
> Undefined values are spotted with a red background, that good. I suggest, you do the same for boolean values. Currently it's not possible to know if a configuration is `false` or an empty string, maybe you can render the boolean `true` and `false` with or style.
> 
> The other point it that it's can be better to have a try/catch block to avoid unclear errors that may happen (but will probably never happen). (not mandatory, but better imo)

I updated output styling.
I don't care strange errors cause in command line I don't think this problem would be critical nor hard to solve.

2022-05-23 08:30 UTC, tom-combet approved these changes
OK for me! Tested and approved. ✔️ 

I see one easy improvement (but not necessary, maybe in an other pull request if someone needs it): add a 'key' option to get the value of one environment variable only. Like this:

```
bin/console fop:environment:get-parameters -k "database_host"

127.0.0.1
```

2022-05-23 20:52 UTC, SebSept approved these changes
👍🏼 Thanks for the job and the patience !

2022-05-23 20:54 UTC, merged