Mcho/add command ungraftmoduleonhook
friends-of-presta/fop_console pull request #60
Opened 2020-08-20 09:23 UTC by Mch0

2020-10-25 18:56 UTC, nenes25 requested changes
Just update the wording :) 
For the code everything seems good.

2020-10-25 18:56 UTC, nenes25 commented on README.md
> +* `fop:graft-module-on-hook` : Graft module on specific hook
Still the old wording ?

2020-10-25 19:37 UTC, okom3pom requested changes

2020-10-25 19:37 UTC, okom3pom commented on src/Commands/UnhookModule.php
> +            ->setHelp('This command allows you to dettach a module from one hook');
Only one T

2020-10-26 07:54 UTC, okom3pom approved these changes

2020-10-27 16:15 UTC, nenes25 approved these changes

2020-11-09 22:19 UTC, SebSept approved these changes
Super, Merci @Mch0 :)

2020-11-10 07:28 UTC, merged