Command configuration
friends-of-presta/fop_console pull request #89
Opened 2021-01-09 22:01 UTC by SebSept

Command to export configuration(s)

2021-01-12 21:07 UTC, SebSept commented
I've done a rapid implementation.
It works.
Can you test it ?
I'll have a few documenation in the readme

2021-01-14 04:59 UTC, SebSept commented
Should check if file already exists before writing.

2021-03-23 13:48 UTC, Mch0 approved these changes
Ok pour moi, pourquoi ne pas aussi ajouter une option pour exporter toutes les configurations ?

2021-03-24 17:08 UTC, SebSept commented
Je suis plus dans l'optique de coder ce qui est utile et pas ce que j'imagine qui pourrait être utile.
Et j'ai pas vu d'interet à cette option, j'y ai bien pensé 😉 mais j'ai pas vu de cas d'utilisation (qui pourrait vraiment arriver).
__Tu penses que ça un intérêt ?__ 
Faut aussi voir que certaines config vont poser problème (url du shop par exemple).

Pour ma part j'ai des cas d'utilisation où je configure un module et quand j'ai la bonne config, je dois la refaire en prod (et en préprod).

2021-03-24 17:50 UTC, Mch0 commented
Je pense que ça peu avoir un intérêt oui, pour sauvegarder les valeurs de la table à un instant T et revenir en arrière si besoin etc, mais comme dit c'est le improvement pas de la nécessite :)

2021-03-24 19:26 UTC, SebSept commented
exact, j'avais pas pensé a cet usage.
Je fais un dump complet dans ces cas là.
Mais ça a du sens 👍🏼

2021-03-26 13:20 UTC, SebSept commented
du coup, on merge cette commande et on voit plus tard pour ajouter l'option, histoire de faire avancer les choses ?

2021-03-26 14:23 UTC, Mch0 commented
Oui ça me va, je laisse @jf-viguier ou @nenes25 faire le merge

2021-03-26 15:17 UTC, jf-viguier commented
- est que les configurations multilang sont traités ? (configuration_lang)
- Est-ce que le multi boutique est traité ? colonne id_shop renseignée ou null ?
- Il faudrait proposer un exemple avec 2 valeurs dans keys stp
- L'aide détaillée devrait également être dans le readme

2021-03-29 09:52 UTC, SebSept commented
merci @jf-viguier pour ces questions, je répond dans la semaine..

2021-04-05 13:57 UTC, SebSept commented
I choose not to implement the --all option because the command rely on `prestashop.adapter.legacy.configuration` service which [do not yet implement this feature](https://github.com/PrestaShop/PrestaShop/blob/be4f8f673dc1a9dcf6ff9b8e120a395cc3038dd9/src/Adapter/Configuration.php#L60).
We could implement it later when it will became available.

I added examples and notes about multishop and multilanguage (both not supported).

2021-04-08 19:22 UTC, nenes25 requested changes
Hello,
Il faudrait corriger la déclaration de la commande d'import qui est manquante :)

2021-04-08 19:22 UTC, nenes25 commented on config/services.yml
> +
Il manque le tag de déclaration de la commande d'import
Elle n'est donc pas disponible :/
![image](https://user-images.githubusercontent.com/7163132/114084236-3a9d8580-98b0-11eb-9f93-c88fc9971aa0.png)

2021-04-08 20:35 UTC, SebSept commented on config/services.yml
> +
arf, j'ai raté ça dans le merge sur github.
corrigé.

2021-04-09 19:38 UTC, nenes25 approved these changes

2021-04-09 19:38 UTC, nenes25 commented
Parfait tout fonctionne bien :)

2021-04-09 20:05 UTC, merged